"""extend quote status enum, add historical quote fields

Revision ID: 5de5ff38282d
Revises: f961a5cb4bc6
Create Date: 2026-08-20 17:12:14.440799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de5ff38282d'
down_revision: Union[str, Sequence[str], None] = 'f961a5cb4bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_dates_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('service_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('historical_total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('quotation_date_text', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('draft', 'sent', 'follow_up_sent', 'new_version_sent', 'waiting', 'approved', 'declined', 'cancelled', 'expired', name='quotestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'sent', 'follow_up_sent', 'new_version_sent', 'waiting', 'approved', 'declined', 'cancelled', 'expired', name='quotestatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('quotation_date_text')
        batch_op.drop_column('historical_total_amount')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('service_description')
        batch_op.drop_column('event_dates_text')

    # ### end Alembic commands ###
