"""initial schema

Revision ID: e19a6560079a
Revises: 
Create Date: 2026-08-19 15:30:11.207125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19a6560079a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.Enum('led_wall', 'logistics', name='producttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pixel_pitch_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('panel_width_mm', sa.Integer(), nullable=True),
    sa.Column('panel_height_mm', sa.Integer(), nullable=True),
    sa.Column('resolution_width_px', sa.Integer(), nullable=True),
    sa.Column('resolution_height_px', sa.Integer(), nullable=True),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_week', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_venue', sa.String(), nullable=True),
    sa.Column('event_start_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotestatus'), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=True)
    op.create_table('quote_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rental_days', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
