"""add external_id, make company_name optional

Revision ID: f961a5cb4bc6
Revises: e19a6560079a
Create Date: 2026-08-19 16:17:15.087493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f961a5cb4bc6'
down_revision: Union[str, Sequence[str], None] = 'e19a6560079a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_external_id'))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
